pipeline {
    agent any
    stages {
        stage('Docker build') {
            steps {
                script {
                    bat "docker build -f FirstPipeline/Dockerfile -t juancdiazd/continuous-integration:latest-${BUILD_ID} FirstPipeline"
                }
            }
        }
        stage('Docker login') {
			steps {
                script {
				   withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',
                   usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                   bat 'docker login -u "$USERNAME" -p "$PASSWORD"'
    }
                } 
			}
		}
        stage('Docker push') {
            steps {
                script {
                    bat "docker push juancdiazd/continuous-integration:latest-${BUILD_ID}"
                }
            }
        }
    }
}