pipeline {
    agent any
    stages {
        stage('docker build') {
            steps {
                script {
                    bat "docker build -f FirstPipeline/Dockerfile -t juancdiazd/continuous-integration:latest-${BUILD_ID} FirstPipeline"
                }
            }
        }
        stage('docker push') {
            withCredentials([usernamePassword( credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
            def registry_url = "registry.hub.docker.com/juancdiazd/continuous-integration:lastest"
            bat "docker login -u $USER -p $PASSWORD ${registry_url}"
            docker.withRegistry("http://${registry_url}", "docker-hub-credentials") 
            steps {
                script {
                    withDockerRegistry([ credentialsId: "docker-hub-credentials", url: "docker.io/juancdiazd/continuous-integration:lastest" ])
                    bat "docker push juancdiazd/continuous-integration:latest-${BUILD_ID}"
                }
            }
        }
    }
}
} 